In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame as df

In [2]:
Order = int(input("숫자를 입력하세요: "))
Zp = [i for i in range(Order)]  # Zp 만들기

Point1 = []       # (x,y,1) x,y는 F의 원소 
Point2 = []       # (x,1,0) x는 F의 원소
Point3 = [[Zp[1],Zp[0],Zp[0]]] # (1,0,0)
    
print("")
print("Field of order", Order,  "=", Zp)
print("")

# Point1 => (x,y,1) 인 경우
for i in range(Order):
    for j in range(Order):
        Point = []
        Point.append(Zp[i])
        Point.append(Zp[j])
        Point.append(Zp[1])
        Point1.append(Point)     
        
# Point2 => (x,1,0) 인 경우
for i in range(Order):
    Point = []
    Point.append(Zp[i])
    Point.append(Zp[1])
    Point.append(Zp[0])
    Point2.append(Point)

Point_set_re = Point1+Point2+Point3
Line_set_re = Point_set_re 

print("Points set :", Point_set_re)
print("")
print("Lines set :", Line_set_re)

숫자를 입력하세요: 3

Field of order 3 = [0, 1, 2]

Points set : [[0, 0, 1], [0, 1, 1], [0, 2, 1], [1, 0, 1], [1, 1, 1], [1, 2, 1], [2, 0, 1], [2, 1, 1], [2, 2, 1], [0, 1, 0], [1, 1, 0], [2, 1, 0], [1, 0, 0]]

Lines set : [[0, 0, 1], [0, 1, 1], [0, 2, 1], [1, 0, 1], [1, 1, 1], [1, 2, 1], [2, 0, 1], [2, 1, 1], [2, 2, 1], [0, 1, 0], [1, 1, 0], [2, 1, 0], [1, 0, 0]]

In [3]:
Line_set = Line_set_re
Point_set = Point_set_re

In [4]:
size = len(Point_set)
Point_set_ind = [1,2,3,4,5,6,7,8,9,10,11,12,13]
Line_set_ind = Point_set_ind

Matrix_des3 = df(data = np.zeros((size,size)), columns = Point_set_ind, index = Line_set_ind,
                 dtype = 'int', copy=False)

In [5]:
# Des(3) 

print(" Lines", "                        Points")
print("")
for i in range(len(Line_set)):
    Incidence_Point = []
    for j in range(len(Point_set)):
        if np.sum(np.array(Line_set[i]*np.array(Point_set[j])))%3 == 0:
            Incidence_Point.append(Point_set[j])
            Matrix_des3.iloc[i, j] = 1   # Matrix
    
    print(Line_set[i] , " = " , Incidence_Point)

 Lines                         Points

[0, 0, 1]  =  [[0, 1, 0], [1, 1, 0], [2, 1, 0], [1, 0, 0]]
[0, 1, 1]  =  [[0, 2, 1], [1, 2, 1], [2, 2, 1], [1, 0, 0]]
[0, 2, 1]  =  [[0, 1, 1], [1, 1, 1], [2, 1, 1], [1, 0, 0]]
[1, 0, 1]  =  [[2, 0, 1], [2, 1, 1], [2, 2, 1], [0, 1, 0]]
[1, 1, 1]  =  [[0, 2, 1], [1, 1, 1], [2, 0, 1], [2, 1, 0]]
[1, 2, 1]  =  [[0, 1, 1], [1, 2, 1], [2, 0, 1], [1, 1, 0]]
[2, 0, 1]  =  [[1, 0, 1], [1, 1, 1], [1, 2, 1], [0, 1, 0]]
[2, 1, 1]  =  [[0, 2, 1], [1, 0, 1], [2, 1, 1], [1, 1, 0]]
[2, 2, 1]  =  [[0, 1, 1], [1, 0, 1], [2, 2, 1], [2, 1, 0]]
[0, 1, 0]  =  [[0, 0, 1], [1, 0, 1], [2, 0, 1], [1, 0, 0]]
[1, 1, 0]  =  [[0, 0, 1], [1, 2, 1], [2, 1, 1], [2, 1, 0]]
[2, 1, 0]  =  [[0, 0, 1], [1, 1, 1], [2, 2, 1], [1, 1, 0]]
[1, 0, 0]  =  [[0, 0, 1], [0, 1, 1], [0, 2, 1], [0, 1, 0]]

In [6]:
Matrix_des3

    1   2   3   4   5   6   7   8   9   10  11  12  13
1    0   0   0   0   0   0   0   0   0   1   1   1   1
2    0   0   1   0   0   1   0   0   1   0   0   0   1
3    0   1   0   0   1   0   0   1   0   0   0   0   1
4    0   0   0   0   0   0   1   1   1   1   0   0   0
5    0   0   1   0   1   0   1   0   0   0   0   1   0
6    0   1   0   0   0   1   1   0   0   0   1   0   0
7    0   0   0   1   1   1   0   0   0   1   0   0   0
8    0   0   1   1   0   0   0   1   0   0   1   0   0
9    0   1   0   1   0   0   0   0   1   0   0   1   0
10   1   0   0   1   0   0   1   0   0   0   0   0   1
11   1   0   0   0   0   1   0   1   0   0   0   1   0
12   1   0   0   0   1   0   0   0   1   0   1   0   0
13   1   1   1   0   0   0   0   0   0   1   0   0   0

In [131]:
# col, row 바꾸는 함수

def change_col(a,b,matrix):
    cols = matrix.columns.tolist()
    for i in range(len(cols)):
        if int(a) == cols[i]:
            tmp_a = i   # a값이 해당하는 index값
        elif int(b) == cols[i]:
            tmp_b = i   # b값이 해당하는 index값
    
    del cols[tmp_a]
    cols.insert(tmp_a,b)
    del cols[tmp_b]
    cols.insert(tmp_b, a)
    matrix = matrix[cols]
    return matrix

def change_row(a,b,matrix):
    rows = matrix.index.tolist()
    
    for i in range(len(rows)):
        if a == rows[i]:
            tmp_a = i
        if b == rows[i]:
            tmp_b = i
            
    del rows[tmp_a]
    rows.insert(tmp_a,b)
    del rows[tmp_b]
    rows.insert(tmp_b,a)
    matrix = matrix.reindex(index=rows)
    return matrix

 # 첫 번째 라인 위에 있는 점들의 위치

# ith row에서 1이 있어야 할 열의 인덱스들의 리스트
def poition_index_of_ith_row(i, matrix, fix_index):
    
    #fix_index = [1,2,4,5]  #초기배치 설정
    one_list = [1,1,1,1]
    for j in range(len(one_list)):
        one_list[j] = i-1
    
    fix_index = [(x+y)%13 if x+y>13 else x+y for x,y in zip(fix_index, one_list)]
    fix_index_real_col_num = []
    for j in range(len(fix_index)):
        fix_index_real_col_num.append(matrix.columns[fix_index[j]-1])
        
    return fix_index_real_col_num

def index_of_one(ind, matrix):
    index_list = []
    for i in range(1, len(matrix)+1):
        if matrix.loc[ind,i] == 1:
            index_list.append(i)
    return index_list  

#j번째 row의 1의 개수를 세준다.(col은 i번째 이상에서만)
def jth_row_CountOne(i, j, matrix):  # j행을 접근해서 i열부터 1의 개수를 세야함 
    
    jth_row = matrix.loc[j] # 접근한 j번째 행의 row
    weight = 0
    
    for k in range(i-1, len(jth_row)):
        if jth_row.iloc[k] == 1:
             weight += 1 
    
    return weight

# weight값을 만족하는 후보 row들의 인덱스 값을 가진 리스트를 반환해주는 함수
def candidate_row_index(i, weight_of_ith, matrix):
    
    row_list= matrix.index.tolist()
    #print("row_list :", row_list)
    sum_value_of_one = weight_of_ith[i-1]
    candidate_list=[]
    
    for k in range(i-1,len(matrix)):
        if sum_value_of_one == jth_row_CountOne(i, row_list[k], matrix):
            candidate_list.append(row_list[k])
            
    return candidate_list

# 한 row의 특정원소 matrix(i,j)에서 j열의 i행 이하의 원소값들을 리스트화 해주는 함수
def element_list_of_rows(row_index, col_index, matrix):
    
    row_index_list = matrix.index.tolist()
    using_row_index_list = []
    for j in range(len(row_index_list)):
        
        if row_index_list[j] == row_index:
            break
        using_row_index_list.append(row_index_list[j])
        
    list = []
    for element in using_row_index_list:
        list.append(matrix.loc[element,col_index])
    return list

# 리스트안에 원소 비교해주는 함수
def check_element(list1, list2):
    check = 0
    for x,y in zip(list1, list2):
        if x != y :
            check +=1
    if check ==0:
        return True
    else:
        return False
    
def list_remove_operation(list1, list2):
    
    list3 = []
    for i in list1:
        if i not in list2:
            list3.append(i)
    return list3

def combination_list(list1, list2):
    
    combination = []
    for x in itertools.permutations(list1,len(list2)):
        group = []
        for pair in zip(x, list2):
            group.append(pair)
        combination.append(group)
    
    return combination

# 각 후보행들마다 열이 잘 바뀌는지 확인해주는 함수
def check_condition(ind, position_index, updated_matrix):
    
    existence_value = False
    
    selected_position_ith_one = index_of_one(ind, updated_matrix)
    
    # 각 리스트끼리 빼준다(공통index 제거)
    ith_one_position = list_remove_operation(selected_position_ith_one, position_index)
    position_index = list_remove_operation(position_index, selected_position_ith_one)
    
    combination = combination_list(ith_one_position, position_index)
     
    for group in combination:
        
        check_list = []
        for pair in group:        
            
            list1 = element_list_of_rows(ind, pair[0], updated_matrix)
            list2 = element_list_of_rows(ind, pair[1], updated_matrix)
            
            if check_element(list1, list2) == True:
                check_list.append(1)
            else:
                break
                
        if len(check_list) == len(group):
            selected_group = group
            
            existence_value = True
            
            return existence_value, selected_group
            break
    
    if existence_value == False:
        return existence_value, []
    
def change_columns(selected_group, updated_matrix):
    
    for i in range(len(selected_group)):

        matrix = change_col(selected_group[i][0], selected_group[i][1], updated_matrix)
        updated_matrix = matrix
    return updated_matrix

In [136]:
Matrix = Matrix_des3

In [150]:
updated_matrix = change_col(1,10,Matrix)
updated_matrix = change_col(3,11,updated_matrix)
updated_matrix = change_col(6,12,updated_matrix)
updated_matrix = change_col(7,13,updated_matrix)

updated_matrix

    10  2   11  4   5   12  13  8   9   1   3   6   7
1    1   0   1   0   0   1   1   0   0   0   0   0   0
2    0   0   0   0   0   0   1   0   1   0   1   1   0
3    0   1   0   0   1   0   1   1   0   0   0   0   0
4    1   0   0   0   0   0   0   1   1   0   0   0   1
5    0   0   0   0   1   1   0   0   0   0   1   0   1
6    0   1   1   0   0   0   0   0   0   0   0   1   1
7    1   0   0   1   1   0   0   0   0   0   0   1   0
8    0   0   1   1   0   0   0   1   0   0   1   0   0
9    0   1   0   1   0   1   0   0   1   0   0   0   0
10   0   0   0   1   0   0   1   0   0   1   0   0   1
11   0   0   0   0   0   1   0   1   0   1   0   1   0
12   0   0   1   0   1   0   0   0   1   1   0   0   0
13   1   1   0   0   0   0   0   0   0   1   1   0   0

In [151]:
weight_of_ith = []

k=1
for i in range(len(updated_matrix)):
    sum = 0
    for j in range(k):
        sum+=updated_matrix.iloc[0,j]
    k+=1
    weight_of_ith.append(sum)

weight_of_ith.reverse() 
weight_of_ith

[4, 4, 4, 4, 4, 4, 4, 3, 2, 2, 2, 1, 1]

In [152]:
import itertools
from itertools import product

fix_index = [1,3,6,7] # 첫 번째 라인 위에 있는 점들의 위치
one_list = [1,1,1,1] # position update 할 때 사용

for i in range(2, len(updated_matrix)):
    ind = updated_matrix.index[i-1] # 접근할 행
    print("i =", i)
    print("ind =", ind)
    position_index = poition_index_of_ith_row(i, updated_matrix, fix_index)
    print("position :", position_index)
    # 후보 열 인덱스 가져온 리스트
    candidate_row_ind_list = candidate_row_index(i, weight_of_ith, updated_matrix)
    print("candidate :", candidate_row_ind_list)
    
    # 각 후보마다 행 바꾸는 작업 진행 & 만약 성공한 행이 있으면 for문 종료
    for j in range(len(candidate_row_ind_list)):
        
        access_row_ind = candidate_row_ind_list[j]
        tmp = updated_matrix
        updated_matrix = change_row(ind,access_row_ind,updated_matrix) # 행 바뀐 행렬
    
        existence, selected_group = check_condition(access_row_ind, position_index, updated_matrix)
        #print(access_row_ind, "==>", existence)
        #print(access_row_ind, "==>", selected_group)
        #print("")
        if existence == True:
            print("바뀐 행 :", access_row_ind)
            break
        else:
            updated_matrix = tmp
            continue
    
# 조합에 해당하는 pair끼리 열 바꾼다.
    print("i번째 조합 =", selected_group)
    updated_matrix = change_columns(selected_group, updated_matrix)
    print("")
updated_matrix

i = 2
ind = 2
position : [2, 4, 13, 8]
candidate : [2, 3, 5, 6, 8, 9, 10, 11, 12]
바뀐 행 : 2
i번째 조합 = [(3, 2), (6, 4), (9, 8)]

i = 3
ind = 3
position : [11, 5, 9, 8]
candidate : [3, 6, 9, 10, 11, 12]
바뀐 행 : 6
i번째 조합 = [(2, 5), (6, 9), (7, 8)]

i = 4
ind = 4
position : [9, 12, 7, 1]
candidate : [3, 9, 10, 11]
바뀐 행 : 9
i번째 조합 = [(2, 7), (4, 1)]

i = 5
ind = 5
position : [7, 13, 4, 5]
candidate : [3, 10, 11]
바뀐 행 : 10
i번째 조합 = [(1, 5)]

i = 6
ind = 3
position : [12, 6, 1, 5]
candidate : [3, 11]
바뀐 행 : 11
i번째 조합 = [(8, 5)]

i = 7
ind = 7
position : [13, 2, 8, 5]
candidate : [3]
바뀐 행 : 3
i번째 조합 = []

i = 8
ind = 8
position : [6, 4, 5, 10]
candidate : [7]
바뀐 행 : 7
i번째 조합 = []

i = 9
ind = 4
position : [2, 1, 10, 3]
candidate : [8, 12, 13]
바뀐 행 : 13
i번째 조합 = []

i = 10
ind = 5
position : [4, 8, 3, 11]
candidate : [8, 12]
바뀐 행 : 8
i번째 조합 = []

i = 11
ind = 5
position : [1, 5, 11, 9]
candidate : [12]
바뀐 행 : 12
i번째 조합 = []

i = 12
ind = 5
position : [8, 10, 9, 7]
candidate : [5, 4]
바뀐 행 : 4
i번째 조합 = []

    10  3   11  9   7   12  13  6   2   4   1   8   5
1    1   0   1   0   0   1   1   0   0   0   0   0   0
2    0   1   0   1   0   0   1   1   0   0   0   0   0
6    0   0   1   0   1   0   0   1   1   0   0   0   0
9    0   0   0   1   0   1   0   0   1   1   0   0   0
10   0   0   0   0   1   0   1   0   0   1   1   0   0
11   0   0   0   0   0   1   0   1   0   0   1   1   0
3    0   0   0   0   0   0   1   0   1   0   0   1   1
7    1   0   0   0   0   0   0   1   0   1   0   0   1
13   1   1   0   0   0   0   0   0   1   0   1   0   0
8    0   1   1   0   0   0   0   0   0   1   0   1   0
12   0   0   1   1   0   0   0   0   0   0   1   0   1
4    1   0   0   1   1   0   0   0   0   0   0   1   0
5    0   1   0   0   1   1   0   0   0   0   0   0   1

In [97]:
i = 3

ind = updated_matrix.index[i-1] # 접근할 행
print("i =", i)
print("ind =", ind)
position_index = poition_index_of_ith_row(i, updated_matrix)
print("position :", position_index)
# 후보 열 인덱스 가져온 리스트
#candidate_row_ind_list = candidate_row_index(i, weight_of_ith, updated_matrix)
#print("candidate :", candidate_row_ind_list)
    
# 각 후보마다 행 바꾸는 작업 진행 & 만약 성공한 행이 있으면 for문 종료
for j in range(i-1,len(updated_matrix)):
        
    access_row_ind = updated_matrix.index[j]
    print(access_row_ind)
    tmp = updated_matrix
    updated_matrix = change_row(ind,access_row_ind,updated_matrix) # 행 바뀐 행렬
    
    existence, selected_group = check_condition(access_row_ind, position_index, updated_matrix)
    #print(access_row_ind, "==>", existence)
    #print(access_row_ind, "==>", selected_group)
    #print("")
    if existence == True:
        print("바뀐 행 :", access_row_ind)
        break
    else:
        updated_matrix = tmp
        continue
    
# 조합에 해당하는 pair끼리 열 바꾼다.
print("i번째 조합 =", selected_group)
updated_matrix = change_columns(selected_group, updated_matrix)
    
updated_matrix

i = 3
ind = 3
position : [2, 5, 9, 4]
3
4
5
6
7
8
9
10
11
12
13
i번째 조합 = []

    10  3   2   11  6   5   7   12  13  9   4   8   1
1    1   0   0   1   0   0   0   1   1   0   0   0   0
2    0   1   0   0   1   0   0   0   1   1   0   0   0
3    0   0   1   0   0   1   0   0   1   0   0   1   0
4    1   0   0   0   0   0   1   0   0   1   0   1   0
5    0   1   0   0   0   1   1   1   0   0   0   0   0
6    0   0   1   1   1   0   1   0   0   0   0   0   0
7    1   0   0   0   1   1   0   0   0   0   1   0   0
8    0   1   0   1   0   0   0   0   0   0   1   1   0
9    0   0   1   0   0   0   0   1   0   1   1   0   0
10   0   0   0   0   0   0   1   0   1   0   1   0   1
11   0   0   0   0   1   0   0   1   0   0   0   1   1
12   0   0   0   1   0   1   0   0   0   1   0   0   1
13   1   1   1   0   0   0   0   0   0   0   0   0   1

In [148]:
fix_index = [1,3,6,7] # 첫 번째 라인 위에 있는 점들의 위치

for i in range(2, len(updated_matrix)):
    ind = updated_matrix.index[i-1] # 접근할 행
    print("i =", i)
    print("ind =", ind)
    position_index = poition_index_of_ith_row(i, updated_matrix, fix_index)
    print("position :", position_index)
    # 후보 열 인덱스 가져온 리스트
    #candidate_row_ind_list = candidate_row_index(i, weight_of_ith, updated_matrix)
    #print("candidate :", candidate_row_ind_list)
    
    # 각 후보마다 행 바꾸는 작업 진행 & 만약 성공한 행이 있으면 for문 종료
    for j in range(i, len(updated_matrix)):
        
        access_row_ind = updated_matrix.index[j-1]
        print("access_row_ind :", access_row_ind)
        tmp = updated_matrix
        updated_matrix = change_row(ind,access_row_ind,updated_matrix) # 행 바뀐 행렬
    
        existence, selected_group = check_condition(access_row_ind, position_index, updated_matrix)
        #print(access_row_ind, "==>", existence)
        #print(access_row_ind, "==>", selected_group)
        #print("")
        if existence == True:
            print("바뀐 행 :", access_row_ind)
            break
        else:
            updated_matrix = tmp
            continue
    
# 조합에 해당하는 pair끼리 열 바꾼다.
    print("i번째 조합 =", selected_group)
    updated_matrix = change_columns(selected_group, updated_matrix)
    print("")
updated_matrix

i = 2
ind = 2
position : [2, 4, 13, 8]
access_row_ind : 2
바뀐 행 : 2
i번째 조합 = [(3, 2), (6, 4), (9, 8)]

i = 3
ind = 3
position : [11, 5, 9, 8]
access_row_ind : 3
access_row_ind : 4
바뀐 행 : 4
i번째 조합 = [(10, 11), (7, 5)]

i = 4
ind = 3
position : [6, 12, 8, 1]
access_row_ind : 3
access_row_ind : 5
바뀐 행 : 5
i번째 조합 = [(3, 6), (7, 8), (5, 1)]

i = 5
ind = 3
position : [8, 13, 5, 2]
access_row_ind : 3
바뀐 행 : 3
i번째 조합 = []

i = 6
ind = 6
position : [12, 9, 2, 4]
access_row_ind : 6
access_row_ind : 7
access_row_ind : 8
access_row_ind : 9
바뀐 행 : 9
i번째 조합 = []

i = 7
ind = 7
position : [13, 7, 4, 1]
access_row_ind : 7
access_row_ind : 8
access_row_ind : 6
access_row_ind : 10
바뀐 행 : 10
i번째 조합 = []

i = 8
ind = 8
position : [9, 5, 1, 11]
access_row_ind : 8
access_row_ind : 6
access_row_ind : 7
access_row_ind : 11
access_row_ind : 12
바뀐 행 : 12
i번째 조합 = []

i = 9
ind = 6
position : [7, 2, 11, 6]
access_row_ind : 6
바뀐 행 : 6
i번째 조합 = []

i = 10
ind = 7
position : [5, 4, 6, 10]
access_row_ind : 7
바뀐 행 : 7
i번째 조합 = []

i = 11
ind = 11
position : [2, 1, 10, 3]
access_row_ind : 11
access_row_ind : 8
i번째 조합 = []

i = 12
ind = 8
position : [4, 11, 3, 8]
access_row_ind : 8
바뀐 행 : 8
i번째 조합 = []

    11  6   10  3   8   12  13  9   7   5   2   4   1
1    1   0   1   0   0   1   1   0   0   0   0   0   0
2    0   1   0   1   0   0   1   1   0   0   0   0   0
4    0   0   1   0   1   0   0   1   1   0   0   0   0
5    0   0   0   1   0   1   0   0   1   1   0   0   0
3    0   0   0   0   1   0   1   0   0   1   1   0   0
9    0   0   0   0   0   1   0   1   0   0   1   1   0
10   0   0   0   0   0   0   1   0   1   0   0   1   1
12   1   0   0   0   0   0   0   1   0   1   0   0   1
6    1   1   0   0   0   0   0   0   1   0   1   0   0
7    0   1   1   0   0   0   0   0   0   1   0   1   0
11   0   1   0   0   1   1   0   0   0   0   0   0   1
8    1   0   0   1   1   0   0   0   0   0   0   1   0
13   0   0   1   1   0   0   0   0   0   0   1   0   1

In [149]:
updated_matrix = change_row(11,13, updated_matrix)
updated_matrix

    11  6   10  3   8   12  13  9   7   5   2   4   1
1    1   0   1   0   0   1   1   0   0   0   0   0   0
2    0   1   0   1   0   0   1   1   0   0   0   0   0
4    0   0   1   0   1   0   0   1   1   0   0   0   0
5    0   0   0   1   0   1   0   0   1   1   0   0   0
3    0   0   0   0   1   0   1   0   0   1   1   0   0
9    0   0   0   0   0   1   0   1   0   0   1   1   0
10   0   0   0   0   0   0   1   0   1   0   0   1   1
12   1   0   0   0   0   0   0   1   0   1   0   0   1
6    1   1   0   0   0   0   0   0   1   0   1   0   0
7    0   1   1   0   0   0   0   0   0   1   0   1   0
13   0   0   1   1   0   0   0   0   0   0   1   0   1
8    1   0   0   1   1   0   0   0   0   0   0   1   0
11   0   1   0   0   1   1   0   0   0   0   0   0   1